include ../../rules.mk

.PHONY: lieder.pdf
lieder.pdf:
	pandoc -o $@ \
		lieder-header.md \
		tochter-zion.md  \
		lieder-pagebreak.md \
		alle-jahre-wieder.md \
		lieder-pagebreak.md \
		suesser-die-glocken.md \
		lieder-pagebreak.md \
		mache-dich-auf.md
